### ISSUE TITLE
C snippets - I cannot find this group

### ISSUE THREAD

**Issue by uyplayer** [marcotrosi/C#3]

**Comment by marcotrosi** [comment]
because it is a private group and I invite personally. Why did you delete your account?

**Comment by uyplayer** [comment]
there is a privacy problom ; so i deleted my account

**Comment by uyplayer** [comment]
let me kmow how can i add you  ? or add the group ?

**Comment by marcotrosi** [comment]
I have to add you to the group. just write me on Telegram. search for my name without space.

**Comment by uyplayer** [comment]
telegram gime me an alarm : sorry you can only send message to mutual contects at the moment

**Comment by marcotrosi** [comment]
then re-join the Unix group. [UnixUserGroup](t.me/UnixUserGroup)
