### ISSUE TITLE
Please, define the audience and objective

### ISSUE THREAD

**Issue by italomaia** [marcotrosi/C#4]
While reading the HelloWorld chapter, I noticed that it has very clear educational goals, but the explanation doesn't seem to target a specific audience. It seems to make assumptions on knowledge that exists and knowledge that doesn't. 
It would be nice to have a clear statement in the project root explaining for who this tutorial is for and what will they learn by reading it. It would also be nice to change the top project description. Doesn't look like a pack of snippets to me.

**Comment by marcotrosi** [comment]
I added some text on the front page. Is this what you had in mind?

**Comment by italomaia** [comment]
Seems good. Thanks!
